notifications:
  email: false

#os: osx

language: minimal

jobs:
  include:
    - os: osx
      language: shell
      sudo: required
      install:
        - pwd
        - ls
        - mv CMakeLists.txt vendor/source/jgrapht-capi/CMakeLists.txt
        - brew cask install graalvm/tap/graalvm-ce-java11
        - export PATH=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.0.0/Contents/Home/bin:"$PATH"
        - gu install native-image
        - brew install swig

script:
  - java -versi
  - native-image --version
  - cmake --version
  - swig -version
  - python3 --version
  - python3 setup.py bdist_wheel
  - pip3 install pytest
  - pip3 install python-jgrapht --no-index -f dist/
  - pytest tests


#    - os: linux  
#    - os: windows
#    - sudo: required
#      services:
#        - docker
#      env: DOCKER_IMAGE=ftsamis/python-jgrapht-builder:1
#           PLAT=manylinux2010_x86_64

#install:
#  - docker pull $DOCKER_IMAGE

#script:
#  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
#  - ls -l dist/
