notifications:
  email: false

#os: osx

language: minimal

jobs:
  include:
    - os: osx
      sudo: required
      install: brew cask install graalvm/tap/graalvm-ce-java11
      env: PATH=/Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.0.0/Contents/Home/bin:"$PATH"
script: java -version
#    - os: linux  
#    - os: windows
#    - sudo: required
#      services:
#        - docker
#      env: DOCKER_IMAGE=ftsamis/python-jgrapht-builder:1
#           PLAT=manylinux2010_x86_64

#install:
#  - docker pull $DOCKER_IMAGE

#script:
#  - docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh
#  - ls -l dist/
